name: Playwright + Allure
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    env:
      SSO_PROD: ${{secrets.SSO_PROD}}
      SSO_STG: ${{secrets.SSO_STG}}
      SSO_QA: ${{secrets.SSO_QA}}
      USER_NAME_PROD: ${{secrets.USER_NAME_PROD}}
      USER_NAME_QA: ${{secrets.USER_NAME_QA}}
      USER_PASSWORD: ${{secrets.USER_PASSWORD}}
      USER_NEW_PASSWORD: ${{secrets.USER_NEW_PASSWORD}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install proyect dependencies
        run: npm ci
      - name: Install Playwright Browsers (Only Chromium)
        run: npx playwright install chromium
      - name: Run All tests
        run: npx playwright test

      - name: Install Java (OpenJDK 17)
        run: sudo apt-get update && sudo apt-get install -y openjdk-17-jre

      - name: Generate Allure report
        run: npx allure generate "allure-results" -o "allure-report" --clean

      - name: Upload Allure HTML
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 30

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: Evidencias de pruebas
          path: test-results
          retention-days: 15
